"""
Export trained weights and MNIST test data for the web presentation.
Run this AFTER training with the C++ program (which saves w0.bin..b2.bin).

Usage:  python export_web_data.py
Output: web_data.js  (included by presentation.html)
"""

import numpy as np
import struct
import json
import os
import sys

NUM_SAMPLES = 200  # number of test images to export

def load_weight_bin(path):
    """Read a weight file saved by the C++ program (u32 rows, u32 cols, f32[] data)."""
    with open(path, 'rb') as f:
        rows = struct.unpack('I', f.read(4))[0]
        cols = struct.unpack('I', f.read(4))[0]
        data = np.frombuffer(f.read(), dtype=np.float32)
    return rows, cols, data.tolist()

def main():
    # ── Check that weight files exist ──────────────────────────────────────────
    weight_files = ['w0.bin', 'w1.bin', 'w2.bin', 'b0.bin', 'b1.bin', 'b2.bin']
    missing = [f for f in weight_files if not os.path.exists(f)]
    if missing:
        print(f"ERROR: Missing weight files: {missing}")
        print("Run the C++ program first to train and save weights.")
        sys.exit(1)

    # ── Load test images and labels ────────────────────────────────────────────
    print("Loading test images...")
    test_images = np.fromfile("test_images.mat", dtype=np.float32).reshape(10000, 784)
    test_labels_raw = np.fromfile("test_labels.mat", dtype=np.float32).reshape(10000)

    # Take subset
    images = test_images[:NUM_SAMPLES]
    labels = test_labels_raw[:NUM_SAMPLES].astype(int).tolist()

    print(f"Exporting {NUM_SAMPLES} test images...")

    # ── Load weights ───────────────────────────────────────────────────────────
    print("Loading trained weights...")
    weights = {}
    names = ['w0', 'w1', 'w2', 'b0', 'b1', 'b2']
    for name in names:
        rows, cols, data = load_weight_bin(f"{name}.bin")
        weights[name] = {'rows': rows, 'cols': cols, 'data': data}
        print(f"  {name}: {rows}x{cols} ({len(data)} params)")

    # ── Write JS data file ─────────────────────────────────────────────────────
    print("Writing web_data.js...")
    with open('web_data.js', 'w') as f:
        f.write('// Auto-generated by export_web_data.py — DO NOT EDIT\n')
        f.write(f'const NUM_SAMPLES = {NUM_SAMPLES};\n')
        f.write(f'const MNIST_LABELS = {json.dumps(labels)};\n')

        # Write images as flat array for efficiency
        flat_images = images.flatten().tolist()
        f.write(f'const MNIST_IMAGES_FLAT = new Float32Array({json.dumps(flat_images)});\n')

        # Write weights
        for name in names:
            w = weights[name]
            f.write(f'const {name.upper()}_ROWS = {w["rows"]};\n')
            f.write(f'const {name.upper()}_COLS = {w["cols"]};\n')
            f.write(f'const {name.upper()}_DATA = new Float32Array({json.dumps(w["data"])});\n')

    size_kb = os.path.getsize('web_data.js') / 1024
    print(f"Done! web_data.js ({size_kb:.0f} KB)")
    print("Open presentation.html in your browser to view the demo.")

if __name__ == '__main__':
    main()
